apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-ui
spec:
  selector:
    matchLabels:
      app: data-svc-deployment
  template:
    metadata:
      labels:
        app: data-svc-deployment
    spec:
      containers:
      - name: 'internal-uic'
        image: snehamore213/internalapp5
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
